controller_list:
  - name: fake_arm_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint2
      - joint3
      - joint4
      - joint5
      - joint6
  - name: fake_gripper_group_controller
    type: $(arg fake_execution_type)
    joints:
      - joint_gripper_left
      - joint_gripper_right
initial:  # Define initial robot poses per group
  - group: arm_group
    pose: deliver_candy
  - group: gripper_group
    pose: open