arm_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint2
    - joint3
    - joint4
    - joint5
    - joint6
  gains:
    joint2:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint3:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint4:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint5:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint6:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_group_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - joint_gripper_left
    - joint_gripper_right
  gains:
    joint_gripper_left:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    joint_gripper_right:
      p: 100
      d: 1
      i: 1
      i_clamp: 1